### ISSUE TITLE
npm start not working.

### ISSUE THREAD

**Issue by DevDorrejo** [prashant7july/whatsapp-chatbot#4]
![image](https://user-images.githubusercontent.com/7697566/89668344-950ebe00-d8ab-11ea-8f83-51932630d462.png)

**Comment by prashant7july** [comment]
Hi Dev, 

Basically have to update ngrok using `npm update ngrok` to resolve this issue.

**Comment by prashant7july** [comment]
Hi Again, Different way to resolve

1. Either using `npm update ngrok` to resolve this issue
2. Or Remove Line 508 to 521 and just use ./ngrok http 3031, Because This one is the best way and even follows the `Single Responsibility Principle` and along with one more reason is that ngrok is only for local tests. My personal preference is this one. Because It support fine grained microservices.
3. Or you can add the https module. but I have no good Idea for that.
